<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CmsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('c_m_s')->truncate();

        $records = [
            [
                'id' => 1,
                'page' => 'about_us',
                'section_name' => 'hero',
                'title_en' => 'Our Goals and Mission:',
                'title_de' => 'Unsere Ziele und Mission:',
                'title_hu' => 'Céljaink és küldetésünk:',
                'sub_title_en' => null,
                'sub_title_de' => null,
                'sub_title_hu' => null,
                'description_en' => 'Experience the chance to win your dream home in Söchau, East Styria, for just €99! At TicketVilla, our goal is to introduce you to the unique Fürstenfeld Thermal Region through our e-book.',
                'description_de' => 'Erleben Sie die Chance, Ihr Traumhaus in der wunderschönen Umgebung von Söchau in der Oststeiermark für nur 99 € zu gewinnen!',
                'description_hu' => 'Tapasztalja meg a lehetőséget, hogy megnyerje álmai otthonát Söchau gyönyörű környezetében mindössze 99 euróért!',
                'link' => null,
                'link_en' => null,
                'link_de' => null,
                'link_hu' => null,
                'image' => 'frontend/images/home-hero-banner.png',
                'video' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'page' => 'home',
                'section_name' => 'hero',
                'title_en' => 'With just one e-book to Your dream home!',
                'title_de' => 'Mit nur einem E-Book zu Ihrem Traumhaus!',
                'title_hu' => 'Egyetlen e-könyvvel álmai otthonába!',
                'sub_title_en' => null,
                'sub_title_de' => null,
                'sub_title_hu' => null,
                'description_en' => 'Become the lucky winner and secure your dream home worth €850,000! All you need is our e-book "Exploring Styria’s Thermen Region Styria 2024".',
                'description_de' => 'Werden Sie glücklicher Gewinner und sichern Sie sich Ihr Traumhaus im Wert von 850.000 Euro!',
                'description_hu' => 'Legyen Ön a szerencsés nyertes, és biztosítsa álmai otthonát 850 000 € értékben!',
                'link' => null,
                'link_en' => null,
                'link_de' => null,
                'link_hu' => null,
                'image' => 'frontend/images/home-hero-banner.png',
                'video' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'page' => 'how_it_works',
                'section_name' => 'hero',
                'title_en' => 'Discover the Process',
                'title_de' => 'Entdecken Sie den Prozess',
                'title_hu' => 'Fedezze fel a folyamatot',
                'sub_title_en' => null,
                'sub_title_de' => null,
                'sub_title_hu' => null,
                'description_en' => 'Learn how you can win your dream house with just one ticket!',
                'description_de' => 'Erfahren Sie, wie Sie mit nur einem Los Ihr Traumhaus gewinnen können!',
                'description_hu' => 'Ismerje meg, hogyan nyerheti meg álmai házát egyetlen jeggyel!',
                'link' => null,
                'link_en' => null,
                'link_de' => null,
                'link_hu' => null,
                'image' => 'frontend/images/home-hero-banner.png',
                'video' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'page' => 'contact',
                'section_name' => 'hero',
                'title_en' => 'Get in Touch',
                'title_de' => 'In Kontakt kommen',
                'title_hu' => 'Felveszi a kapcsolatot',
                'sub_title_en' => null,
                'sub_title_de' => null,
                'sub_title_hu' => null,
                'description_en' => 'We are here to assist you with any inquiries or concerns you may have.',
                'description_de' => 'Wir sind für Sie da und unterstützen Sie bei allen Fragen und Anliegen.',
                'description_hu' => 'Azért vagyunk itt, hogy segítsünk Önnek bármilyen kérdése vagy aggálya esetén.',
                'link' => null,
                'link_en' => null,
                'link_de' => null,
                'link_hu' => null,
                'image' => 'frontend/images/home-hero-banner.png',
                'video' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'page' => 'the_house',
                'section_name' => 'hero',
                'title_en' => 'The House',
                'title_de' => 'Das Haus',
                'title_hu' => 'A ház',
                'sub_title_en' => null,
                'sub_title_de' => null,
                'sub_title_hu' => null,
                'description_en' => 'Welcome to The House, where dreams come true. This stunning property offers the perfect blend of luxury, modern design, and spacious living.',
                'description_de' => 'Willkommen im Das Haus, wo Träume wahr werden.',
                'description_hu' => 'Üdvözöljük a házban, ahol az álmok valóra válnak.',
                'link' => null,
                'link_en' => null,
                'link_de' => null,
                'link_hu' => null,
                'image' => 'frontend/images/home-hero-banner.png',
                'video' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'page' => null,
                'section_name' => 'three_d_house_tour',
                'title_en' => null,
                'title_de' => null,
                'title_hu' => null,
                'sub_title_en' => null,
                'sub_title_de' => null,
                'sub_title_hu' => null,
                'description_en' => null,
                'description_de' => null,
                'description_hu' => null,
                'link' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'link_en' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'link_de' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'link_hu' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'image' => null,
                'video' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'page' => null,
                'section_name' => 'visit_your_new_home',
                'title_en' => null,
                'title_de' => null,
                'title_hu' => null,
                'sub_title_en' => null,
                'sub_title_de' => null,
                'sub_title_hu' => null,
                'description_en' => null,
                'description_de' => null,
                'description_hu' => null,
                'link' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'link_en' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'link_de' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'link_hu' => 'https://www.youtube.com/embed/HW-OMaFxWXs',
                'image' => null,
                'video' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($records as $record) {
            DB::table('c_m_s')->insert($record);
        }
    }
}
