<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

class TheProcessesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        $the_process_images = public_path('uploads/the-process');
        $the_process_icon = public_path('uploads/the-process-icon');
        $existsProcessImage = public_path('seed-files/the-process');
        $existsProcessIcon = public_path('seed-files/the-process-icon');

        if (File::exists($the_process_images)) {
            File::deleteDirectory($the_process_images);
        }
        File::makeDirectory($the_process_images);
        File::copyDirectory($existsProcessImage, $the_process_images);
        if (File::exists($the_process_icon)) {
            File::deleteDirectory($the_process_icon);
        }
        File::makeDirectory($the_process_icon);
        File::copyDirectory($existsProcessIcon, $the_process_icon);
        \DB::table('the_processes')->insert([
            0 => [
                'id' => 1,
                'title_en' => 'We Are Officially Starting To Sell The E-Book(En)',
                'title_de' => 'We Are Officially Starting To Sell The E-Book(De)',
                'title_hu' => 'We Are Officially Starting To Sell The E-Book(Hu)',
                'description_en' => 'The eBooks are now on sale worldwide, accepting a wide range of payment methods including methods including Euros, Dollars and many other currencies to suit everyone\'s preferences. Each e-book comes with a free numbered entry ticket for the Dream House prize draw.',
                'description_de' => 'The eBooks are now on sale worldwide, accepting a wide range of payment methods including methods including Euros, Dollars and many other currencies to suit everyone\'s preferences. Each e-book comes with a free numbered entry ticket for the Dream House prize draw.',
                'description_hu' => 'The eBooks are now on sale worldwide, accepting a wide range of payment methods including methods including Euros, Dollars and many other currencies to suit everyone\'s preferences. Each e-book comes with a free numbered entry ticket for the Dream House prize draw.',
                'image' => 'uploads/the-process/1718441221-9ee05516-c83c-4b67-8d31-d4608ee2e4ed.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718342472-2f73e4ba-91a4-411c-b032-095a1ad0089f.png',
                'icon_top_text_en' => 'E-BOOK SALE STARTS',
                'icon_top_text_de' => 'E-BOOK SALE STARTS',
                'icon_top_text_hu' => 'E-BOOK SALE STARTS',
                'icon_bottom_text_en' => null,
                'icon_bottom_text_de' => null,
                'icon_bottom_text_hu' => null,
                'sort_id' => '0',
                'button_type' => 'none',
                'status' => 'active',
                'created_at' => '2024-06-14 05:21:12',
                'updated_at' => '2024-06-15 08:47:01',
            ],
            1 => [
                'id' => 2,
                'title_en' => 'One Insider Dashboard For All Your Needs.(En)',
                'title_de' => 'One Insider Dashboard For All Your Needs.(De)',
                'title_hu' => 'One Insider Dashboard For All Your Needs.(Hu)',
                'description_en' => 'Explore exposés, buy tickets, join our affiliate programme to earn money, view live statistics, news updates and more. Our dedicated dashboard streamlines the entire process for seamless management.',
                'description_de' => 'Explore exposés, buy tickets, join our affiliate programme to earn money, view live statistics, news updates and more. Our dedicated dashboard streamlines the entire process for seamless management.',
                'description_hu' => 'Explore exposés, buy tickets, join our affiliate programme to earn money, view live statistics, news updates and more. Our dedicated dashboard streamlines the entire process for seamless management.',
                'image' => 'uploads/the-process/1718441232-4d35ef22-aafa-4690-8a08-652cd6d8881f.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718428961-828b9f05-a46f-4176-a737-38b49a71c39d.png',
                'icon_top_text_en' => 'ALL YOUR NEEDS',
                'icon_top_text_de' => 'ALL YOUR NEEDS',
                'icon_top_text_hu' => 'ALL YOUR NEEDS',
                'icon_bottom_text_en' => null,
                'icon_bottom_text_de' => null,
                'icon_bottom_text_hu' => null,
                'sort_id' => '1',
                'button_type' => 'buy_now',
                'status' => 'active',
                'created_at' => '2024-06-15 05:22:41',
                'updated_at' => '2024-06-15 08:47:12',
            ],
            2 => [
                'id' => 3,
                'title_en' => 'We Have Reached Our Goal, The Raffle Is About To Start! (En)',
                'title_de' => 'We Have Reached Our Goal, The Raffle Is About To Start! (De)',
                'title_hu' => 'We Have Reached Our Goal, The Raffle Is About To Start! (Hu)',
                'description_en' => 'We have reached our goal and the raffle can begin. But wait, there is more! If we reach our goal within the target time frame of 6 months, the lucky winner will receive substantial bonuses. Bonus milestones are at 17,000 and 20,000 tickets sold. Keep scrolling',
                'description_de' => 'We have reached our goal and the raffle can begin. But wait, there is more! If we reach our goal within the target time frame of 6 months, the lucky winner will receive substantial bonuses. Bonus milestones are at 17,000 and 20,000 tickets sold. Keep scrolling',
                'description_hu' => 'We have reached our goal and the raffle can begin. But wait, there is more! If we reach our goal within the target time frame of 6 months, the lucky winner will receive substantial bonuses. Bonus milestones are at 17,000 and 20,000 tickets sold. Keep scrolling',
                'image' => 'uploads/the-process/1718441243-bf8abbab-9bfe-4575-8e1f-f0e6e1dbea6f.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718429067-d7788627-f268-4ebd-8e6d-e30b30bd09ed.png',
                'icon_top_text_en' => '15.000 E-BOOK SOLD',
                'icon_top_text_de' => '15.000 E-BOOK SOLD',
                'icon_top_text_hu' => '15.000 E-BOOK SOLD',
                'icon_bottom_text_en' => null,
                'icon_bottom_text_de' => null,
                'icon_bottom_text_hu' => null,
                'sort_id' => '2',
                'button_type' => 'buy_now',
                'status' => 'active',
                'created_at' => '2024-06-15 05:24:27',
                'updated_at' => '2024-06-15 08:47:23',
            ],
            3 => [
                'id' => 4,
                'title_en' => '€20,000 Extra Furniture Voucher. (En)',
                'title_de' => '€20,000 Extra Furniture Voucher. (De)',
                'title_hu' => '€20,000 Extra Furniture Voucher. (Hu)',
                'description_en' => 'At this point, the lucky winner will receive an extra €20,000 furniture voucher to go with the house! You might think there is nothing left to be desired. A luxurious house for just €99, plus a €20,000 furniture voucher or the winner can choose the €20,000 cash. What more could you ask for?',
                'description_de' => 'At this point, the lucky winner will receive an extra €20,000 furniture voucher to go with the house! You might think there is nothing left to be desired. A luxurious house for just €99, plus a €20,000 furniture voucher or the winner can choose the €20,000 cash. What more could you ask for?',
                'description_hu' => 'At this point, the lucky winner will receive an extra €20,000 furniture voucher to go with the house! You might think there is nothing left to be desired. A luxurious house for just €99, plus a €20,000 furniture voucher or the winner can choose the €20,000 cash. What more could you ask for?',
                'image' => 'uploads/the-process/1718441251-05904512-00ef-4993-a794-8f8b41ced3b9.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718429214-89ba2ad7-b723-4e4e-b560-b4e4c7e7e652.png',
                'icon_top_text_en' => '17.000 TICKETS SOLD',
                'icon_top_text_de' => '17.000 TICKETS SOLD',
                'icon_top_text_hu' => '17.000 TICKETS SOLD',
                'icon_bottom_text_en' => 'BONUS',
                'icon_bottom_text_de' => 'BONUS',
                'icon_bottom_text_hu' => 'BONUS',
                'sort_id' => '3',
                'button_type' => 'buy_now',
                'status' => 'active',
                'created_at' => '2024-06-15 05:26:54',
                'updated_at' => '2024-06-15 08:47:31',
            ],
            4 => [
                'id' => 5,
                'title_en' => 'Proven Fair, Legally Secure(En)',
                'title_de' => 'Proven Fair, Legally Secure(De)',
                'title_hu' => 'Proven Fair, Legally Secure(Hu)',
                'description_en' => 'Experience peace of mind with our raffle: proven fair and legally secure. Enter for a chance to win your dream home!',
                'description_de' => 'Experience peace of mind with our raffle: proven fair and legally secure. Enter for a chance to win your dream home!',
                'description_hu' => 'Experience peace of mind with our raffle: proven fair and legally secure. Enter for a chance to win your dream home!',
                'image' => 'uploads/the-process/1718441259-1798cd55-c884-4d29-911f-24db5972e744.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718429566-9a90413d-99f0-4dc9-9cd1-26a7cd2aaa38.png',
                'icon_top_text_en' => 'GOOD TO KNOW',
                'icon_top_text_de' => 'GOOD TO KNOW',
                'icon_top_text_hu' => 'GOOD TO KNOW',
                'icon_bottom_text_en' => null,
                'icon_bottom_text_de' => null,
                'icon_bottom_text_hu' => null,
                'sort_id' => '4',
                'button_type' => 'learn_more',
                'status' => 'active',
                'created_at' => '2024-06-15 05:32:46',
                'updated_at' => '2024-06-15 08:47:39',
            ],
            5 => [
                'id' => 6,
                'title_en' => 'Installation Of An Additional Solar-Heated Indoor Pool.(En)',
                'title_de' => 'Installation Of An Additional Solar-Heated Indoor Pool.(De)',
                'title_hu' => 'Installation Of An Additional Solar-Heated Indoor Pool.(Hu)',
                'description_en' => 'Yes! When we reach 20,000 tickets sold, the winner will not only receive the house and the €20,000 voucher, but also a solar heated, fully indoor swimming pool for you, your family and friends to enjoy. The value of this is €60,000.00 or the winner can choose to claim the cash price instead.',
                'description_de' => 'Yes! When we reach 20,000 tickets sold, the winner will not only receive the house and the €20,000 voucher, but also a solar heated, fully indoor swimming pool for you, your family and friends to enjoy. The value of this is €60,000.00 or the winner can choose to claim the cash price instead.',
                'description_hu' => 'Yes! When we reach 20,000 tickets sold, the winner will not only receive the house and the €20,000 voucher, but also a solar heated, fully indoor swimming pool for you, your family and friends to enjoy. The value of this is €60,000.00 or the winner can choose to claim the cash price instead.',
                'image' => 'uploads/the-process/1718441266-29a2a539-7d5b-4666-8dd5-7b524b6a84c2.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718429678-53bb19a6-ed45-447f-8a23-97f55d01e291.png',
                'icon_top_text_en' => '20.000 TICKETS SOLD',
                'icon_top_text_de' => '20.000 TICKETS SOLD',
                'icon_top_text_hu' => '20.000 TICKETS SOLD',
                'icon_bottom_text_en' => 'BONUS',
                'icon_bottom_text_de' => 'BONUS',
                'icon_bottom_text_hu' => 'BONUS',
                'sort_id' => '5',
                'button_type' => 'learn_more',
                'status' => 'active',
                'created_at' => '2024-06-15 05:34:38',
                'updated_at' => '2024-06-15 08:47:46',
            ],
            6 => [
                'id' => 7,
                'title_en' => 'The Odds Are 9332 Times Better Than The Lottery(En)',
                'title_de' => 'The Odds Are 9332 Times Better Than The Lottery(De)',
                'title_hu' => 'The Odds Are 9332 Times Better Than The Lottery(Hu)',
                'description_en' => 'Experience peace of mind with our raffle: proven fair and legally secure. Enter for a chance to win your dream home!',
                'description_de' => 'Experience peace of mind with our raffle: proven fair and legally secure. Enter for a chance to win your dream home!',
                'description_hu' => 'Experience peace of mind with our raffle: proven fair and legally secure. Enter for a chance to win your dream home!',
                'image' => 'uploads/the-process/1718441276-57c0f0f5-4a67-4381-991f-8e8c68eda947.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718429782-92c555d0-7ca9-4516-9b05-61795a279cf9.png',
                'icon_top_text_en' => 'LIVE DRAWING',
                'icon_top_text_de' => 'LIVE DRAWING',
                'icon_top_text_hu' => 'LIVE DRAWING',
                'icon_bottom_text_en' => null,
                'icon_bottom_text_de' => null,
                'icon_bottom_text_hu' => null,
                'sort_id' => '6',
                'button_type' => 'learn_more',
                'status' => 'active',
                'created_at' => '2024-06-15 05:36:22',
                'updated_at' => '2024-06-15 08:47:56',
            ],
            7 => [
                'id' => 8,
                'title_en' => 'We Guarantee 100% Transparency! The Winner Is Drawn Live.(En)',
                'title_de' => 'We Guarantee 100% Transparency! The Winner Is Drawn Live.(De)',
                'title_hu' => 'We Guarantee 100% Transparency! The Winner Is Drawn Live.(Hu)',
                'description_en' => 'Pledge complete transparency with us! Our commitment to fairness means that the winner will be drawn live on YouTube by a Cypriot Notary Public so that the excitement can be viewed by all. Don\'t miss your chance to win big!',
                'description_de' => 'Pledge complete transparency with us! Our commitment to fairness means that the winner will be drawn live on YouTube by a Cypriot Notary Public so that the excitement can be viewed by all. Don\'t miss your chance to win big!',
                'description_hu' => 'Pledge complete transparency with us! Our commitment to fairness means that the winner will be drawn live on YouTube by a Cypriot Notary Public so that the excitement can be viewed by all. Don\'t miss your chance to win big!',
                'image' => 'uploads/the-process/1718441284-4b28dd5e-4a84-4775-b7c5-18bddb86c86e.jpg',
                'video_url_en' => null,
                'video_url_de' => null,
                'video_url_hu' => null,
                'icon' => 'uploads/the-process-icon/1718429885-34016d40-a8fa-4f38-b714-f37747abcbf9.png',
                'icon_top_text_en' => null,
                'icon_top_text_de' => null,
                'icon_top_text_hu' => null,
                'icon_bottom_text_en' => null,
                'icon_bottom_text_de' => null,
                'icon_bottom_text_hu' => null,
                'sort_id' => '7',
                'button_type' => 'both',
                'status' => 'active',
                'created_at' => '2024-06-15 05:38:05',
                'updated_at' => '2024-06-15 08:48:04',
            ],
        ]);

    }
}
